#!/usr/bin/env python3
from subprocess import PIPE, run
import sys
def out(command):
    result = run(command, stdout=PIPE, stderr=PIPE, universal_newlines=True, shell=True)
    return (result.stdout).strip()
