#!/usr/bin/env python3
from subprocess import PIPE, run
import sys
def out(command):
    result = run(command, stdout=PIPE, stderr=PIPE, universal_newlines=True, shell=True)
    return (result.stdout).strip()



# acceptable branch types list
branchTypes = ["develop","master","release","feature","patch","private"]
devBranches = ["release","feature","patch","private"]
# obtain current branch name
currentBranchName = out("git rev-parse --abbrev-ref HEAD")
# Sync effort
#https://www.atlassian.com/git/tutorials/comparing-workflows
# change to remote on version.txt -> no push


# report hyphen error
if currentBranchName != "develop" and currentBranchName != "master" and currentBranchName.find('-') == -1:
    print("[ERROR] Branch name not follow naming conventions.\n[HINT] Non master/develop branches must include hyphen.\n[HINT] Must follow [branchtype]-[descriptivename] format")
    print("[ABORT] Aborting. Commit not created.")
    sys.exit(1)
# split at hyphen
currentBranchType = currentBranchName.split('-')[0]
if not currentBranchType in branchTypes:
    print("[ERROR] Branch name not follow naming conventions.\n[HINT] Non master/develop branches must include hyphen.\n[HINT] Must follow [branchtype]-[descriptivename] format")
    print("[ABORT] Aborting. Commit not created.")
    sys.exit(1)
sys.exit(0)